apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app.kubernetes.io/part-of: reef
    app.kubernetes.io/component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: reef
        app.kubernetes.io/component: celery
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: celery
          image: ghcr.io/ietf-tools/reef-backend:$APP_IMAGE_TAG
          imagePullPolicy: Always
          env:
            - name: CONTAINER_ROLE
              value: celery
            - name: CELERY_APP
              value: reef
          envFrom:
            - secretRef:
                name: reef-secrets-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
      terminationGracePeriodSeconds: 600
