#!/bin/bash

# Ensure the script runs from its own directory.
dirname=$(dirname "$0")
if [ "$dirname" = "." ] || [ "$dirname" = "" ]; then
    :
else
    echo "Changing to directory $dirname"
    cd "$dirname" || exit 1
fi

read -p "Stop and remove all containers, volumes and images for this project? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cd ..
    echo "Shutting down any instance still running and purging images..."
    docker compose down -v --rmi all
    cd docker
    echo "Done!"
fi
