#!/bin/bash

# Usage info
show_help() {
    cat << EOF
Usage: ${0##*/} [-h] [-p PORT] [-r]
Run the Pink dev environment using docker compose.

    -h          display this help and exit
    -p PORT     use a custom HTTP port for Pink
    -r          force rebuild the app container

EOF
}

CUSTOM_PORT=8088
FORCE_REBUILD=0

while getopts "hp:r" opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        p)
            CUSTOM_PORT=$OPTARG
            echo "Using custom port $CUSTOM_PORT..."
            ;;
        r)
            FORCE_REBUILD=1
            echo "Will force rebuild the app container..."
            ;;
        *)
            CUSTOM_PORT=8088
            echo "Using port 8088..."
            ;;
    esac
done

# Ensure the run script is in our directory.
dirname=$(dirname "$0")
if [ "$dirname" = "." ] || [ "$dirname" = "" ]; then
    :
else
    echo "Changing to directory $dirname"
    cd "$dirname" || exit 1
fi

# Remove mounted temp directories
rm -rf __pycache__

# Create the extended docker-compose definition
sed -e "s/CUSTOM_PORT/$CUSTOM_PORT/" \
	<docker-compose.extend.yml \
	>docker-compose.extend-custom.yml
cd ..

# Set UID/GID mappings
NEW_UID=$(id -u)
NEW_GID=$(id -g)
if [ "$NEW_UID" -gt 0 ]; then
    echo "Will use the following user/group mapping:"
    echo "USER ID: $NEW_UID"
    echo "GROUP ID: $NEW_GID"
else
    echo "Running as root, will use the default user/group mapping..."
    echo "NOT RECOMMENDED - you may experience permission issues."
    NEW_UID=1000
    NEW_GID=1000
fi

COMPOSE="docker compose -f docker-compose.yml -f docker/docker-compose.extend-custom.yml"

# Build / rebuild containers
if [ "$FORCE_REBUILD" == 1 ]; then
    $COMPOSE down
    $COMPOSE rm -f
    $COMPOSE build --no-cache --pull --build-arg USER_UID="$NEW_UID" --build-arg USER_GID="$NEW_GID"
    $COMPOSE up -d --force-recreate
else
    $COMPOSE build --build-arg USER_UID="$NEW_UID" --build-arg USER_GID="$NEW_GID"
    $COMPOSE up -d
fi

# Output the database port
echo "Database exposed on port:"
docker compose port db 5432

# Start the init script
docker compose exec app /bin/zsh /docker-init.sh

# Stop containers on exit
docker compose stop
cd docker
rm -f docker-compose.extend-custom.yml
