# Generated by Django 5.2.17 on 2026-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docsets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentset",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="public",
                help_text="Sets are public: a title and its membership are readable "
                "by anyone with the link. Private is kept for staff to unpublish one.",
                max_length=16,
            ),
        ),
    ]
