# Generated by Django 5.2.16 on 2026-08-20 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "docsets",
            "0006_remove_documentset_unique_document_set_slug_per_owner_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentset",
            name="visibility",
        ),
    ]
