# Generated by Django 5.2.16 on 2026-08-06 03:22

import json

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import migrations, models

from subscriptions.models import normalize_params


def normalize_and_dedupe(apps, schema_editor):
    """Canonicalize params and drop duplicates before the constraint lands.

    Uses the current normalize_params rather than a frozen copy: the point is
    to bring existing rows up to the rules the constraint is about to enforce.
    """
    Subscription = apps.get_model("subscriptions", "Subscription")
    seen = set()
    # Oldest first, so the subscription a user made first is the one kept.
    for row in Subscription.objects.order_by("created_at", "id").iterator():
        try:
            params = normalize_params(row.kind, row.params)
        except ValidationError:
            # A shape the new rules reject. Leave it for a human to look at
            # rather than rewrite or discard someone's subscription, but still
            # dedupe it, or the constraint cannot be added at all.
            params = row.params

        key = (row.user_id, row.kind, json.dumps(params, sort_keys=True))
        if key in seen:
            row.delete()
            continue
        seen.add(key)

        if params != row.params:
            row.params = params
            row.save(update_fields=["params"])


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_subscription_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_and_dedupe, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "params"), name="unique_subscription_per_user"
            ),
        ),
    ]
