# Generated by Django 5.2.17 on 2026-08-25 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docsets", "0007_remove_documentset_visibility"),
        ("subjects", "0001_initial"),
        ("subscriptions", "0005_drop_subject_tag_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription_per_user",
        ),
        migrations.AddField(
            model_name="subscription",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="subjects.subject",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="kind",
            field=models.CharField(
                choices=[
                    ("new_rfc", "Any new RFC"),
                    ("by_status", "New RFC by status"),
                    ("obsoleted", "RFC obsoleted or made historic"),
                    ("rfc", "Changes to one specific RFC"),
                    ("set", "Changes to anything in a document set"),
                    ("subject", "Changes to anything carrying a subject"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "params", "document_set", "subject"),
                name="unique_subscription_per_user",
                nulls_distinct=False,
            ),
        ),
    ]
