# Generated by Django 5.2.17 on 2026-08-31 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_alter_subscription_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="verified",
        ),
    ]
