apiVersion: v1
kind: ConfigMap
metadata:
  name: reef-config
data:
  REEF_ALLOWED_HOSTS: "reef.staging.ietf.org"
  # Point the DB host at the staging database service or managed endpoint.
  REEF_DB_HOST: "postgres"
  NUXT_PUBLIC_OIDC_CLIENT_ID: "" # staging Authentik client id
  REEF_OIDC_RP_CLIENT_ID: "" # staging Authentik client id
